package ec.puntonet.pincidencias.modelo;
// Generated 07-abr-2021 12:12:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private String nombreCli;
     private String identificacionCli;
     private String contactoPrincipalCli;
     private String contactoSecundarioCli;
     private String direccionCli;
     private String mailCli;
     private Integer tipoCli;
     private Integer estadoCli;
     private Integer eliminadoCli;
     private Date fechaRegistroCli;
     private Set ipClientes = new HashSet(0);
     private Set tickets = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String identificacionCli) {
        this.identificacionCli = identificacionCli;
    }
    public Cliente(String nombreCli, String identificacionCli, String contactoPrincipalCli, String contactoSecundarioCli, String direccionCli, String mailCli, Integer tipoCli, Integer estadoCli, Integer eliminadoCli, Date fechaRegistroCli, Set ipClientes, Set tickets) {
       this.nombreCli = nombreCli;
       this.identificacionCli = identificacionCli;
       this.contactoPrincipalCli = contactoPrincipalCli;
       this.contactoSecundarioCli = contactoSecundarioCli;
       this.direccionCli = direccionCli;
       this.mailCli = mailCli;
       this.tipoCli = tipoCli;
       this.estadoCli = estadoCli;
       this.eliminadoCli = eliminadoCli;
       this.fechaRegistroCli = fechaRegistroCli;
       this.ipClientes = ipClientes;
       this.tickets = tickets;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombreCli() {
        return this.nombreCli;
    }
    
    public void setNombreCli(String nombreCli) {
        this.nombreCli = nombreCli;
    }
    public String getIdentificacionCli() {
        return this.identificacionCli;
    }
    
    public void setIdentificacionCli(String identificacionCli) {
        this.identificacionCli = identificacionCli;
    }
    public String getContactoPrincipalCli() {
        return this.contactoPrincipalCli;
    }
    
    public void setContactoPrincipalCli(String contactoPrincipalCli) {
        this.contactoPrincipalCli = contactoPrincipalCli;
    }
    public String getContactoSecundarioCli() {
        return this.contactoSecundarioCli;
    }
    
    public void setContactoSecundarioCli(String contactoSecundarioCli) {
        this.contactoSecundarioCli = contactoSecundarioCli;
    }
    public String getDireccionCli() {
        return this.direccionCli;
    }
    
    public void setDireccionCli(String direccionCli) {
        this.direccionCli = direccionCli;
    }
    public String getMailCli() {
        return this.mailCli;
    }
    
    public void setMailCli(String mailCli) {
        this.mailCli = mailCli;
    }
    public Integer getTipoCli() {
        return this.tipoCli;
    }
    
    public void setTipoCli(Integer tipoCli) {
        this.tipoCli = tipoCli;
    }
    public Integer getEstadoCli() {
        return this.estadoCli;
    }
    
    public void setEstadoCli(Integer estadoCli) {
        this.estadoCli = estadoCli;
    }
    public Integer getEliminadoCli() {
        return this.eliminadoCli;
    }
    
    public void setEliminadoCli(Integer eliminadoCli) {
        this.eliminadoCli = eliminadoCli;
    }
    public Date getFechaRegistroCli() {
        return this.fechaRegistroCli;
    }
    
    public void setFechaRegistroCli(Date fechaRegistroCli) {
        this.fechaRegistroCli = fechaRegistroCli;
    }
    public Set getIpClientes() {
        return this.ipClientes;
    }
    
    public void setIpClientes(Set ipClientes) {
        this.ipClientes = ipClientes;
    }
    public Set getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set tickets) {
        this.tickets = tickets;
    }




}


