package ec.puntonet.pincidencias.modelo;
// Generated 07-abr-2021 12:12:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer idEmpleado;
     private String nombreEmp;
     private String identificacionEmp;
     private String contactoEmp;
     private String mailEmp;
     private Integer tipoEmp;
     private Integer estadoEmp;
     private Integer eliminadoEmp;
     private Date fechaRegistroEmp;
     private Set usuarios = new HashSet(0);
     private Set tickets = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(String identificacionEmp) {
        this.identificacionEmp = identificacionEmp;
    }
    public Empleado(String nombreEmp, String identificacionEmp, String contactoEmp, String mailEmp, Integer tipoEmp, Integer estadoEmp, Integer eliminadoEmp, Date fechaRegistroEmp, Set usuarios, Set tickets) {
       this.nombreEmp = nombreEmp;
       this.identificacionEmp = identificacionEmp;
       this.contactoEmp = contactoEmp;
       this.mailEmp = mailEmp;
       this.tipoEmp = tipoEmp;
       this.estadoEmp = estadoEmp;
       this.eliminadoEmp = eliminadoEmp;
       this.fechaRegistroEmp = fechaRegistroEmp;
       this.usuarios = usuarios;
       this.tickets = tickets;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getNombreEmp() {
        return this.nombreEmp;
    }
    
    public void setNombreEmp(String nombreEmp) {
        this.nombreEmp = nombreEmp;
    }
    public String getIdentificacionEmp() {
        return this.identificacionEmp;
    }
    
    public void setIdentificacionEmp(String identificacionEmp) {
        this.identificacionEmp = identificacionEmp;
    }
    public String getContactoEmp() {
        return this.contactoEmp;
    }
    
    public void setContactoEmp(String contactoEmp) {
        this.contactoEmp = contactoEmp;
    }
    public String getMailEmp() {
        return this.mailEmp;
    }
    
    public void setMailEmp(String mailEmp) {
        this.mailEmp = mailEmp;
    }
    public Integer getTipoEmp() {
        return this.tipoEmp;
    }
    
    public void setTipoEmp(Integer tipoEmp) {
        this.tipoEmp = tipoEmp;
    }
    public Integer getEstadoEmp() {
        return this.estadoEmp;
    }
    
    public void setEstadoEmp(Integer estadoEmp) {
        this.estadoEmp = estadoEmp;
    }
    public Integer getEliminadoEmp() {
        return this.eliminadoEmp;
    }
    
    public void setEliminadoEmp(Integer eliminadoEmp) {
        this.eliminadoEmp = eliminadoEmp;
    }
    public Date getFechaRegistroEmp() {
        return this.fechaRegistroEmp;
    }
    
    public void setFechaRegistroEmp(Date fechaRegistroEmp) {
        this.fechaRegistroEmp = fechaRegistroEmp;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set tickets) {
        this.tickets = tickets;
    }




}


