package ec.puntonet.pincidencias.modelo;
// Generated 07-abr-2021 12:12:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Incidencia generated by hbm2java
 */
public class Incidencia  implements java.io.Serializable {


     private Integer idIncidencia;
     private String nombreInc;
     private String departamentoInc;
     private String duracionInc;
     private String prioridadInc;
     private Integer estadoInc;
     private Set tickets = new HashSet(0);

    public Incidencia() {
    }

    public Incidencia(String nombreInc, String departamentoInc, String duracionInc, String prioridadInc, Integer estadoInc, Set tickets) {
       this.nombreInc = nombreInc;
       this.departamentoInc = departamentoInc;
       this.duracionInc = duracionInc;
       this.prioridadInc = prioridadInc;
       this.estadoInc = estadoInc;
       this.tickets = tickets;
    }
   
    public Integer getIdIncidencia() {
        return this.idIncidencia;
    }
    
    public void setIdIncidencia(Integer idIncidencia) {
        this.idIncidencia = idIncidencia;
    }
    public String getNombreInc() {
        return this.nombreInc;
    }
    
    public void setNombreInc(String nombreInc) {
        this.nombreInc = nombreInc;
    }
    public String getDepartamentoInc() {
        return this.departamentoInc;
    }
    
    public void setDepartamentoInc(String departamentoInc) {
        this.departamentoInc = departamentoInc;
    }
    public String getDuracionInc() {
        return this.duracionInc;
    }
    
    public void setDuracionInc(String duracionInc) {
        this.duracionInc = duracionInc;
    }
    public String getPrioridadInc() {
        return this.prioridadInc;
    }
    
    public void setPrioridadInc(String prioridadInc) {
        this.prioridadInc = prioridadInc;
    }
    public Integer getEstadoInc() {
        return this.estadoInc;
    }
    
    public void setEstadoInc(Integer estadoInc) {
        this.estadoInc = estadoInc;
    }
    public Set getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set tickets) {
        this.tickets = tickets;
    }

}


