package ec.puntonet.pincidencias.modelo;
// Generated 07-abr-2021 12:12:00 by Hibernate Tools 4.3.1



/**
 * IpCliente generated by hbm2java
 */
public class IpCliente  implements java.io.Serializable {


     private Integer idIpCliente;
     private Cliente cliente;
     private Ips ips;

    public IpCliente() {
    }

    public IpCliente(Cliente cliente, Ips ips) {
       this.cliente = cliente;
       this.ips = ips;
    }
   
    public Integer getIdIpCliente() {
        return this.idIpCliente;
    }
    
    public void setIdIpCliente(Integer idIpCliente) {
        this.idIpCliente = idIpCliente;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Ips getIps() {
        return this.ips;
    }
    
    public void setIps(Ips ips) {
        this.ips = ips;
    }




}


