package ec.puntonet.pincidencias.modelo;
// Generated 07-abr-2021 12:12:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ips generated by hbm2java
 */
public class Ips  implements java.io.Serializable {


     private Integer idIps;
     private String ip;
     private Set ipClientes = new HashSet(0);

    public Ips() {
    }

    public Ips(String ip, Set ipClientes) {
       this.ip = ip;
       this.ipClientes = ipClientes;
    }
   
    public Integer getIdIps() {
        return this.idIps;
    }
    
    public void setIdIps(Integer idIps) {
        this.idIps = idIps;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public Set getIpClientes() {
        return this.ipClientes;
    }
    
    public void setIpClientes(Set ipClientes) {
        this.ipClientes = ipClientes;
    }




}


