package ec.puntonet.pincidencias.modelo;
// Generated 07-abr-2021 12:12:00 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Ticket generated by hbm2java
 */
public class Ticket implements java.io.Serializable {

    private Integer idTicket;
    private Cliente cliente;
    private Empleado empleado;
    private Incidencia incidencia;
    private String numeroTic;
    private Integer estadoTic;
    private Date fechaRegistroTic;
    private String contactoComunicacionTic;
    private String medioComunicacionTic;
    private String observacionTic;
    private Integer eliminadoTic;

    public Ticket() {
    }

    public Ticket(Cliente cliente, Empleado empleado, Incidencia incidencia, String numeroTic) {
        this.cliente = cliente;
        this.empleado = empleado;
        this.incidencia = incidencia;
        this.numeroTic = numeroTic;
    }

    public Ticket(Cliente cliente, Empleado empleado, Incidencia incidencia, String numeroTic, Integer estadoTic, Date fechaRegistroTic, String contactoComunicacionTic, String medioComunicacionTic, String observacionTic, Integer eliminadoTic) {
        this.cliente = cliente;
        this.empleado = empleado;
        this.incidencia = incidencia;
        this.numeroTic = numeroTic;
        this.estadoTic = estadoTic;
        this.fechaRegistroTic = fechaRegistroTic;
        this.contactoComunicacionTic = contactoComunicacionTic;
        this.medioComunicacionTic = medioComunicacionTic;
        this.observacionTic = observacionTic;
        this.eliminadoTic = eliminadoTic;
    }

    public Integer getIdTicket() {
        return this.idTicket;
    }

    public void setIdTicket(Integer idTicket) {
        this.idTicket = idTicket;
    }

    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Empleado getEmpleado() {
        return this.empleado;
    }

    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    public Incidencia getIncidencia() {
        return this.incidencia;
    }

    public void setIncidencia(Incidencia incidencia) {
        this.incidencia = incidencia;
    }

    public String getNumeroTic() {
        return this.numeroTic;
    }

    public void setNumeroTic(String numeroTic) {
        this.numeroTic = numeroTic;
    }

    public Integer getEstadoTic() {
        return this.estadoTic;
    }

    public void setEstadoTic(Integer estadoTic) {
        this.estadoTic = estadoTic;
    }

    public Date getFechaRegistroTic() {
        return this.fechaRegistroTic;
    }

    public void setFechaRegistroTic(Date fechaRegistroTic) {
        this.fechaRegistroTic = fechaRegistroTic;
    }

    public String getContactoComunicacionTic() {
        return this.contactoComunicacionTic;
    }

    public void setContactoComunicacionTic(String contactoComunicacionTic) {
        this.contactoComunicacionTic = contactoComunicacionTic;
    }

    public String getMedioComunicacionTic() {
        return this.medioComunicacionTic;
    }

    public void setMedioComunicacionTic(String medioComunicacionTic) {
        this.medioComunicacionTic = medioComunicacionTic;
    }

    public String getObservacionTic() {
        return this.observacionTic;
    }

    public void setObservacionTic(String observacionTic) {
        this.observacionTic = observacionTic;
    }

    public Integer getEliminadoTic() {
        return eliminadoTic;
    }

    public void setEliminadoTic(Integer eliminadoTic) {
        this.eliminadoTic = eliminadoTic;
    }
    
    

    public String estadoToString() {
        String respuesta = "";
        if (this.estadoTic == 0) {
            respuesta = "Abierto";
        } else if (this.estadoTic == 1) {
            respuesta = "Vencido";
        } else if (this.estadoTic == 2) {
            respuesta = "Escalonado";
        } else if (this.estadoTic == 3) {
            respuesta = "Cerrado";
        } else {
            respuesta = "Desconocido";
        }
        return respuesta;
    }

}
