package ec.puntonet.pincidencias.modelo;
// Generated 07-abr-2021 12:12:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Empleado empleado;
     private String nombreUsu;
     private String claveUsu;
     private Integer estadoUsu;
     private Date fechaRegistroUsu;

    public Usuario() {
    }

	
    public Usuario(Empleado empleado) {
        this.empleado = empleado;
    }
    public Usuario(Empleado empleado, String nombreUsu, String claveUsu, Integer estadoUsu, Date fechaRegistroUsu) {
       this.empleado = empleado;
       this.nombreUsu = nombreUsu;
       this.claveUsu = claveUsu;
       this.estadoUsu = estadoUsu;
       this.fechaRegistroUsu = fechaRegistroUsu;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getNombreUsu() {
        return this.nombreUsu;
    }
    
    public void setNombreUsu(String nombreUsu) {
        this.nombreUsu = nombreUsu;
    }
    public String getClaveUsu() {
        return this.claveUsu;
    }
    
    public void setClaveUsu(String claveUsu) {
        this.claveUsu = claveUsu;
    }
    public Integer getEstadoUsu() {
        return this.estadoUsu;
    }
    
    public void setEstadoUsu(Integer estadoUsu) {
        this.estadoUsu = estadoUsu;
    }
    public Date getFechaRegistroUsu() {
        return this.fechaRegistroUsu;
    }
    
    public void setFechaRegistroUsu(Date fechaRegistroUsu) {
        this.fechaRegistroUsu = fechaRegistroUsu;
    }




}


